---

checkpoint:
    save_checkpoint: True
    save_path: checkpoints/model.pth
    load_checkpoint: False
    load_path: checkpoints/model.pth

dataset:
    images_dir: E:/DocLayNet_core/PNG/
    train_labels_file: E:/DocLayNet_core/COCO/train.json
    val_labels_file: E:/DocLayNet_core/COCO/val.json
    test_labels_file: E:/DocLayNet_core/COCO/test.json
    anchors_file: data/anchors.csv
    num_classes: 11
    image_size: 1025
    doc_categories: ['scientific_articles']
    apply_augmentations: False

model:
    fpn_channels: 768
    backbone: microsoft/dit-base

hyperparameters:
    train:
        epochs: 1000
        learning_rate: 1.0e-4
        weight_decay: 0.01
        momentum: 0.9
        gradient_accumulation_steps: 128
        frozen_epochs: 2
        scheduler:
            enabled: False
            scheduler_fn: ExponentialLR
            gamma: 0.98
        early_stopping:
            enabled: True
            patience: 3
            restore_best_weights: True
    test:
        confidence_threshold: 0.05
        map_iou_threshold: 0.5
        nms_iou_threshold: 0.45

dataloader:
    train:
        shuffle: True
        batch_size: 8
        num_workers: 2
        pin_memory: True
        drop_last: True
    val:
        shuffle: False
        batch_size: 8
        num_workers: 2
        pin_memory: True
        drop_last: False
    test:
        shuffle: False
        batch_size: 8
        num_workers: 2
        pin_memory: True
        drop_last: False

wandb:
    enabled: True
    watch_model: False
    project_name: document-layout-analysis
    entity: "iosonopersia" # user or team name
    resume_run: False
    resume_run_id: "" # wandb run id to resume

...
